# Generated by Django 5.1 on 2024-08-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_lista_rename_comprado_producto_marcado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='prueba.lista'),
        ),
    ]
